# set up the default terminal
ENV["TERM"]="linux"

Vagrant.configure("2") do |config|
  
  # set the image for the vagrant box
  config.vm.box = "generic/opensuse15"
  ## Set the image version
  # config.vm.box_version = "15.2.31.247"
  config.vm.provider "vmware_desktop"
  # st the static IP for the vagrant box
  config.vm.network "private_network", ip: "172.16.193.250"
  config.vm.hostname = "server.local"
  
  # consifure the parameters for VirtualBox provider
  config.vm.provider "vmware_desktop" do |vd|
    vd.vmx["memsize"] = "4096"
    vd.vmx["numvcpus"] = 4
    vd.linked_clone = false
  end
end
