# set up the default terminal
ENV["TERM"]="linux"

Vagrant.configure("2") do |config|
  
  # set the image for the vagrant box
  config.vm.box = "generic/opensuse15"
  # st the static IP for the vagrant box
  config.vm.network "private_network", ip: "172.16.193.250"
  config.vm.hostname = "server.local"
  
  # configure the parameters for VMware Desktop provider
  config.vm.provider "vmware_desktop" do |vd|
    vd.vmx["memsize"] = "4096"
    vd.vmx["numvcpus"] = 4
    vd.linked_clone = false
  end
  # configure parameters for LibVirt provider
  config.vm.provider "libvirt" do |lv|
    lv.memory = 4096
    lv.cpus = 4
  end

end
