# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  # st the static IP for the vagrant box
  config.vm.network "private_network", ip: "10.0.254.2"
  config.vm.hostname = "ubuntu.server.local"
  # Adding SSH Public Keys
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/authorized_keys").first.strip
  config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false 
  # configure the parameters for VMware provider
  config.vm.provider "vmware_desktop" do |vd|
    vd.vmx["memsize"] = "2048"
    vd.vmx["numvcpus"] = 2
    vd.linked_clone = false
    vd.nat_device = "vmnet8"
  end
  # configure parameters for LibVirt provider
  config.vm.provider "libvirt" do |lv|
    lv.memory = 2048
    lv.cpus = 2
  end
end
