# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  # st the static IP for the vagrant box
  config.vm.network "private_network", ip: "172.16.193.250"
  config.vm.hostname = "ubuntu.server.local"
  
  # configure the parameters for VMware provider
  config.vm.provider "vmware_desktop" do |vd|
    vd.vmx["memsize"] = "2048"
    vd.vmx["numvcpus"] = 2
    vd.linked_clone = false
  end
  # configure parameters for LibVirt provider
  config.vm.provider "libvirt" do |lv|
    lv.memory = 2048
    lv.cpus = 2
  end
end
